#include "bsp_fdcan.h"
static bsp_status_t validate(const bsp_fdcan_t *m){if(!m)return BSP_STATUS_INVALID_ARGUMENT;return m->is_initialized?BSP_STATUS_OK:BSP_STATUS_NOT_INITIALIZED;}
static bool length_ok(uint8_t n){return n<=8||n==12||n==16||n==20||n==24||n==32||n==48||n==64;}
static bool frame_ok(const bsp_fdcan_frame_t*f){return f&&length_ok(f->data_length)&&
 ((f->id_type==BSP_CAN_ID_STANDARD&&f->identifier<=0x7FFU)||(f->id_type==BSP_CAN_ID_EXTENDED&&f->identifier<=0x1FFFFFFFU))&&
 (f->frame_type==BSP_CAN_FRAME_DATA||f->frame_type==BSP_CAN_FRAME_REMOTE)&&
 (f->format==BSP_FDCAN_FORMAT_CLASSIC||f->format==BSP_FDCAN_FORMAT_FD_NO_BRS||f->format==BSP_FDCAN_FORMAT_FD_BRS)&&
 (f->format!=BSP_FDCAN_FORMAT_CLASSIC||f->data_length<=8);}
bsp_status_t bsp_fdcan_init(bsp_fdcan_t*m,const bsp_fdcan_config_t*c){bsp_status_t s;if(!m||!c||!c->device_handle||!c->driver_ops||!c->driver_ops->start||!c->driver_ops->stop||!c->driver_ops->configure_filter||!c->driver_ops->transmit||!c->driver_ops->receive)return BSP_STATUS_INVALID_ARGUMENT;*m=(bsp_fdcan_t){0};if(c->driver_ops->init){s=c->driver_ops->init(c->device_handle);if(s!=BSP_STATUS_OK)return s;}m->device_handle=c->device_handle;m->driver_ops=c->driver_ops;m->callback=c->callback;m->user_context=c->user_context;m->is_initialized=true;return BSP_STATUS_OK;}
bsp_status_t bsp_fdcan_deinit(bsp_fdcan_t*m){bsp_status_t s=validate(m);if(s!=BSP_STATUS_OK)return s;s=m->driver_ops->deinit?m->driver_ops->deinit(m->device_handle):BSP_STATUS_OK;if(s==BSP_STATUS_OK)m->is_initialized=false;return s;}
bsp_status_t bsp_fdcan_set_callback(bsp_fdcan_t*m,bsp_event_callback_t cb,void*ctx){bsp_status_t s=validate(m);if(s!=BSP_STATUS_OK)return s;m->callback=cb;m->user_context=ctx;return BSP_STATUS_OK;}
bsp_status_t bsp_fdcan_start(bsp_fdcan_t*m){bsp_status_t s=validate(m);return s==BSP_STATUS_OK?m->driver_ops->start(m->device_handle):s;}
bsp_status_t bsp_fdcan_stop(bsp_fdcan_t*m){bsp_status_t s=validate(m);return s==BSP_STATUS_OK?m->driver_ops->stop(m->device_handle):s;}
bsp_status_t bsp_fdcan_configure_filter(bsp_fdcan_t*m,const bsp_can_filter_t*f){bsp_status_t s=validate(m);if(s!=BSP_STATUS_OK)return s;if(!f||((f->receive_fifo!=BSP_CAN_RX_FIFO_0)&&(f->receive_fifo!=BSP_CAN_RX_FIFO_1))||!((f->id_type==BSP_CAN_ID_STANDARD&&f->identifier<=0x7FFU&&f->mask<=0x7FFU)||(f->id_type==BSP_CAN_ID_EXTENDED&&f->identifier<=0x1FFFFFFFU&&f->mask<=0x1FFFFFFFU)))return BSP_STATUS_INVALID_ARGUMENT;return m->driver_ops->configure_filter(m->device_handle,f);}
bsp_status_t bsp_fdcan_transmit(bsp_fdcan_t*m,const bsp_fdcan_frame_t*f,uint32_t t){bsp_status_t s=validate(m);if(s!=BSP_STATUS_OK)return s;return frame_ok(f)?m->driver_ops->transmit(m->device_handle,f,t):BSP_STATUS_OUT_OF_RANGE;}
bsp_status_t bsp_fdcan_receive(bsp_fdcan_t*m,bsp_can_receive_fifo_t q,bsp_fdcan_frame_t*f){bsp_status_t s=validate(m);if(s!=BSP_STATUS_OK)return s;if(!f||(q!=BSP_CAN_RX_FIFO_0&&q!=BSP_CAN_RX_FIFO_1))return BSP_STATUS_INVALID_ARGUMENT;s=m->driver_ops->receive(m->device_handle,q,f);return s!=BSP_STATUS_OK?s:(frame_ok(f)?BSP_STATUS_OK:BSP_STATUS_IO_ERROR);}
bsp_status_t bsp_fdcan_get_protocol_status(const bsp_fdcan_t*m,bsp_fdcan_protocol_status_t*p){bsp_status_t s=validate(m);if(s!=BSP_STATUS_OK)return s;if(!p)return BSP_STATUS_INVALID_ARGUMENT;return m->driver_ops->get_protocol_status?m->driver_ops->get_protocol_status(m->device_handle,p):BSP_STATUS_UNSUPPORTED;}
bsp_status_t bsp_fdcan_get_transmit_free_level(const bsp_fdcan_t*m,uint32_t*l){bsp_status_t s=validate(m);if(s!=BSP_STATUS_OK)return s;if(!l)return BSP_STATUS_INVALID_ARGUMENT;return m->driver_ops->get_transmit_free_level?m->driver_ops->get_transmit_free_level(m->device_handle,l):BSP_STATUS_UNSUPPORTED;}
void bsp_fdcan_notify(bsp_fdcan_t*m,bsp_event_t e,bsp_status_t s,size_t n){if(m&&m->is_initialized&&m->callback)m->callback(e,s,n,m->user_context);}
